version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "7627:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}